#ifndef UDIALD_DEVICECONFIG_H_
#define UDIALD_DEVICECONFIG_H_

#include "udiald.h"

/// ****************************
/// MODEM CONFIGURATION PROFILES
/// ****************************
//
// Do not include this file from anywhere else than modem.c, since that
// will cause this data to be duplicated in the final binary. If you
// need anything from here, go through a function in modem.c.

// Modesetting commands for Huawei modems using the SYSCFG commands.
// CDMA/EVDO-only modems aparrently need the PREFMODE command
//
// Values are mode,preference,bands,roaming,srvdomain
// mode=2: Automatic
// mode=13: GSM (2G)
// mode=14: WCDMA (3G
// mode=16: No change
// preference=0: automatic
// preference=1: Prefer GSM
// preference=2: Prefer WCDMA
// preference=3: No change
// bands=3FFFFFFF: Allow all bands (or no change, specs aren't clear)
// roaming=2: No change
// srvdomain=2: No change
#define HUAWEI_SYSCFG_MODECMD { \
	[UDIALD_MODE_AUTO] = "AT^SYSCFG=2,0,3FFFFFFF,2,4\r", \
	[UDIALD_FORCE_UMTS] = "AT^SYSCFG=14,2,3FFFFFFF,2,4\r", \
	[UDIALD_FORCE_GPRS] = "AT^SYSCFG=13,1,3FFFFFFF,2,4\r", \
	[UDIALD_PREFER_UMTS] = "AT^SYSCFG=2,2,3FFFFFFF,2,4\r", \
	[UDIALD_PREFER_GPRS] = "AT^SYSCFG=2,1,3FFFFFFF,2,4\r", \
}

// Modesetting commands for ZTE modems
// Values are cm_mode,net_sel_mode,pref_acq
// cm_mode=0: Automatic
// cm_mode=1: GSM only
// cm_mode=2: UMTS only
// net_sel_mode is read-only and related to AT+COPS network selection
// pref_acq=0: Automatic order
// pref_acq=1: GSM, then UMTS
// pref_acq=2: UMTS, then GSM
#define ZTE_ZSNT_MODECMD { \
	[UDIALD_MODE_AUTO] = "AT+ZSNT=0,0,0\r", \
	[UDIALD_FORCE_UMTS] = "AT+ZSNT=2,0,0\r", \
	[UDIALD_FORCE_GPRS] = "AT+ZSNT=1,0,0\r", \
	[UDIALD_PREFER_UMTS] = "AT+ZSNT=0,0,2\r", \
	[UDIALD_PREFER_GPRS] = "AT+ZSNT=0,0,1\r", \
}

/* Make sure that the correct ordering of this array is observed: First
 * specific devices, then generic per-vendor profiles and lastly generic
 * per-driver profiles.
 *
 * When autoselecting a profile from this list, the first entry that has
 * all of its conditions (vendor, device, driver) matched will be used.
 *
 * Also note that the name of a profile should never change, since
 * users might have a profile selected for their device, which should
 * remain working after an upgrade. The description can always be
 * changed.
 */
static const struct udiald_profile profiles[] = {
	{
		.name   = "0BDB3705G",
		.desc   = "Ericsson F3705G",
		.vendor = 0x0bdb,
		.device = 0x1900,
		.cfg = {
			.ctlidx = 1,
			.datidx = 0,
			.modecmd = {
				[UDIALD_MODE_AUTO] = "AT+CFUN=1\r",
				[UDIALD_FORCE_UMTS] = "AT+CFUN=6\r",
				[UDIALD_FORCE_GPRS] = "AT+CFUN=5\r",
			},
			.dialcmd = "ATD*99***1#\r",
		},
	},

	{
		.name   = "1BBB000",
		.desc   = "Alcatel X060s",
		.vendor = 0x1bbb,
		.device = 0x0000,
		.cfg = {
			.ctlidx = 1,
			.datidx = 2,
			.modecmd = {
				[UDIALD_MODE_AUTO] = "",
			},
			.dialcmd = "ATD*99***1#\r",
		},
	},
	{
		.name   = "12D11506",
		.desc   = "Huawei E367",
		.vendor = 0x12d1,
		.device = 0x1506,
		.cfg = {
			.ctlidx = 2,
			.datidx = 0,
			.modecmd = HUAWEI_SYSCFG_MODECMD,
			.dialcmd = "ATD*99***1#\r",
		},
	},
	{
		.name   = "19D20055",
		.desc   = "ZTE K3520-Z",
		.vendor = 0x19d2,
		.device = 0x0055,
		.cfg = {
			.ctlidx = 2,
			.datidx = 0,
			.modecmd = ZTE_ZSNT_MODECMD,
			.dialcmd = "ATD*99***1#\r",
		},
	},

// Autogenerated Huawei profiles. These are generated from the udev
// config file shipped in the official Huawei linux driver. These only
// contain a meaningful control and data index, no mode commands.
// Since these automtic profiles are placed below the specific profiles
// above, any changes can be made by adding another profile above,
// instead of changing them in deviceconfig_huawei.h.
#include "deviceconfig_huawei.h"

// VENDOR DEFAULT PROFILES
	{
		.name   = "12D1",
		.desc   = "Huawei generic",
		.vendor = 0x12d1,
		.flags  = UDIALD_PROFILE_NODEVICE,
		.cfg = {
			.ctlidx = 1,
			.datidx = 0,
			.modecmd = HUAWEI_SYSCFG_MODECMD,
			.dialcmd = "ATD*99***1#\r",
		},
	},
	{
		.name   = "19D2",
		.desc   = "ZTE generic",
		.vendor = 0x19d2,
		.flags  = UDIALD_PROFILE_NODEVICE,
		.cfg = {
			.ctlidx = 1,
			.datidx = 2,
			.modecmd = ZTE_ZSNT_MODECMD,
			.dialcmd = "ATD*99***1#\r",
		},
	},
// DRIVER PROFILES
	{
		.name   = "option",
		.desc   = "Option generic",
		.driver = "option",
		.flags  = UDIALD_PROFILE_NOVENDOR | UDIALD_PROFILE_NODEVICE,
		.cfg = {
			.ctlidx = 1,
			.datidx = 0,
			.modecmd = {
				[UDIALD_MODE_AUTO] = "",
			},
			.dialcmd = "ATD*99***1#\r",
		},
	},
	{
		.name   = "sierra",
		.desc   = "Sierra generic",
		.driver = "sierra",
		.flags  = UDIALD_PROFILE_NOVENDOR | UDIALD_PROFILE_NODEVICE,
		.cfg = {
			.ctlidx = 0,
			.datidx = 2,
			.modecmd = {
				[UDIALD_MODE_AUTO] = "",
			},
			.dialcmd = "ATD*99***1#\r",
		},
	},
	{
		.name   = "hso",
		.desc   = "HSO generic",
		.driver = "hso",
		.flags  = UDIALD_PROFILE_NOVENDOR | UDIALD_PROFILE_NODEVICE,
		.cfg = {
			.ctlidx = 0,
			.datidx = 3,
			.modecmd = {
				[UDIALD_MODE_AUTO] = "at_opsys=2,2\r",	// Set auto = prefer UMTS
				[UDIALD_FORCE_UMTS] = "at_opsys=1,2\r",
				[UDIALD_FORCE_GPRS] = "at_opsys=0,2\r",
				[UDIALD_PREFER_UMTS] = "at_opsys=2,2\r",
				[UDIALD_PREFER_GPRS] = "at_opsys=3,2\r",
			},
			.dialcmd = "ATD*99***1#\r",
		},
	},
	{
		.name   = "cdc_acm",
		.desc   = "CDC generic",
		.driver = "cdc_acm",
		.flags  = UDIALD_PROFILE_NOVENDOR | UDIALD_PROFILE_NODEVICE,
		.cfg = {
			/* These are just copied from the option generic
			 * profile */
			.ctlidx = 1,
			.datidx = 0,
			.modecmd = {
				[UDIALD_MODE_AUTO] = "",
			},
			.dialcmd = "ATD*99***1#\r",
		},
	},
	{
		.name   = "usbserial",
		.desc   = "USB serial generic",
		.driver = "usbserial",
		.flags  = UDIALD_PROFILE_NOVENDOR | UDIALD_PROFILE_NODEVICE,
		.cfg = {
			.ctlidx = 0,
			.datidx = 2,
			.modecmd = {
				[UDIALD_MODE_AUTO] = "",
			},
			.dialcmd = "ATD*99***1#\r",
		},
	},
};

#endif /* UDIALD_DEVICECONFIG_H_ */
